from slide_analysis.utils.tile_class import Tile
from slide_analysis.utils.functions import compose
from slide_analysis.utils.functions import get_descriptor_class_by_name
from slide_analysis.utils.functions import get_tiles_coords_from_indexes
