DESCRIPTOR_DIRECTORY_PATH = '../descriptor_apply_service'
CHOSEN_DESCRIPTOR = 'chosen_descriptor'
DESCRIPTOR_PARAMS = 'descriptor_params'
CHOSEN_SIMILARITY = 'chosen_similarity'
SIMILARITY_PARAMS = 'similarity_params'
CHOSEN_N = 'chosen_n'
CHOSEN_N_DEFAULT_VALUE = 10
SETTINGS_PARAMS = {CHOSEN_DESCRIPTOR, DESCRIPTOR_PARAMS, CHOSEN_SIMILARITY, SIMILARITY_PARAMS, CHOSEN_N}
