from slide_analysis.similarities.chi2_similarity_class import Chi2Similarity
from slide_analysis.similarities.euclidean_similarity_class import EuclideanSimilarity
from slide_analysis.similarities.linear_similarity_class import LinearSimilarity

all_similarities = [LinearSimilarity, EuclideanSimilarity, Chi2Similarity]
