# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'slide_analysis/UI/view/settings_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SettingsDialog(object):
    def setupUi(self, SettingsDialog):
        SettingsDialog.setObjectName("SettingsDialog")
        SettingsDialog.resize(427, 336)
        self.gridLayout = QtWidgets.QGridLayout(SettingsDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.settings_tab_widget = QtWidgets.QTabWidget(SettingsDialog)
        self.settings_tab_widget.setTabPosition(QtWidgets.QTabWidget.North)
        self.settings_tab_widget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.settings_tab_widget.setObjectName("settings_tab_widget")
        self.descriptor_settings_tab = QtWidgets.QWidget()
        self.descriptor_settings_tab.setObjectName("descriptor_settings_tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.descriptor_settings_tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.choose_descriptors_combo_box = QtWidgets.QComboBox(self.descriptor_settings_tab)
        self.choose_descriptors_combo_box.setObjectName("choose_descriptors_combo_box")
        self.gridLayout_2.addWidget(self.choose_descriptors_combo_box, 2, 0, 1, 1)
        self.extra_descriptor_settings_layout = QtWidgets.QGridLayout()
        self.extra_descriptor_settings_layout.setObjectName("extra_descriptor_settings_layout")
        self.gridLayout_2.addLayout(self.extra_descriptor_settings_layout, 3, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 0, 1, 1)
        self.choose_descriptors_label = QtWidgets.QLabel(self.descriptor_settings_tab)
        self.choose_descriptors_label.setAlignment(QtCore.Qt.AlignCenter)
        self.choose_descriptors_label.setObjectName("choose_descriptors_label")
        self.gridLayout_2.addWidget(self.choose_descriptors_label, 1, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 4, 0, 1, 1)
        self.settings_tab_widget.addTab(self.descriptor_settings_tab, "")
        self.similar_images_settings_tab = QtWidgets.QWidget()
        self.similar_images_settings_tab.setObjectName("similar_images_settings_tab")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.similar_images_settings_tab)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.similar_images_count_text_label = QtWidgets.QLabel(self.similar_images_settings_tab)
        self.similar_images_count_text_label.setAlignment(QtCore.Qt.AlignCenter)
        self.similar_images_count_text_label.setObjectName("similar_images_count_text_label")
        self.gridLayout_5.addWidget(self.similar_images_count_text_label, 2, 0, 1, 2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem2, 7, 0, 1, 1)
        self.similar_images_count_slider = QtWidgets.QSlider(self.similar_images_settings_tab)
        self.similar_images_count_slider.setMaximum(50)
        self.similar_images_count_slider.setOrientation(QtCore.Qt.Horizontal)
        self.similar_images_count_slider.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.similar_images_count_slider.setTickInterval(1)
        self.similar_images_count_slider.setObjectName("similar_images_count_slider")
        self.gridLayout_5.addWidget(self.similar_images_count_slider, 3, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem3, 1, 0, 1, 1)
        self.similar_images_columns_selection_text_label = QtWidgets.QLabel(self.similar_images_settings_tab)
        self.similar_images_columns_selection_text_label.setAlignment(QtCore.Qt.AlignCenter)
        self.similar_images_columns_selection_text_label.setObjectName("similar_images_columns_selection_text_label")
        self.gridLayout_5.addWidget(self.similar_images_columns_selection_text_label, 5, 0, 1, 2)
        self.similar_images_count_label = QtWidgets.QLabel(self.similar_images_settings_tab)
        self.similar_images_count_label.setObjectName("similar_images_count_label")
        self.gridLayout_5.addWidget(self.similar_images_count_label, 3, 1, 1, 1)
        self.similar_images_columns_count_slider = QtWidgets.QSlider(self.similar_images_settings_tab)
        self.similar_images_columns_count_slider.setMaximum(4)
        self.similar_images_columns_count_slider.setSingleStep(1)
        self.similar_images_columns_count_slider.setOrientation(QtCore.Qt.Horizontal)
        self.similar_images_columns_count_slider.setObjectName("similar_images_columns_count_slider")
        self.gridLayout_5.addWidget(self.similar_images_columns_count_slider, 6, 0, 1, 1)
        self.similar_images_columns_count_text_label = QtWidgets.QLabel(self.similar_images_settings_tab)
        self.similar_images_columns_count_text_label.setAlignment(QtCore.Qt.AlignCenter)
        self.similar_images_columns_count_text_label.setObjectName("similar_images_columns_count_text_label")
        self.gridLayout_5.addWidget(self.similar_images_columns_count_text_label, 6, 1, 1, 1)
        self.settings_tab_widget.addTab(self.similar_images_settings_tab, "")
        self.similarities_settings = QtWidgets.QWidget()
        self.similarities_settings.setObjectName("similarities_settings")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.similarities_settings)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem4 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem4)
        self.choose_similarities_label_2 = QtWidgets.QLabel(self.similarities_settings)
        self.choose_similarities_label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.choose_similarities_label_2.setObjectName("choose_similarities_label_2")
        self.verticalLayout_2.addWidget(self.choose_similarities_label_2)
        self.choose_similarities_combo_box = QtWidgets.QComboBox(self.similarities_settings)
        self.choose_similarities_combo_box.setObjectName("choose_similarities_combo_box")
        self.verticalLayout_2.addWidget(self.choose_similarities_combo_box)
        self.extra_similarities_settings_layout = QtWidgets.QGridLayout()
        self.extra_similarities_settings_layout.setObjectName("extra_similarities_settings_layout")
        self.verticalLayout_2.addLayout(self.extra_similarities_settings_layout)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem5)
        self.settings_tab_widget.addTab(self.similarities_settings, "")
        self.gridLayout.addWidget(self.settings_tab_widget, 1, 0, 1, 1)
        self.settings_conformation_buttons = QtWidgets.QDialogButtonBox(SettingsDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.settings_conformation_buttons.sizePolicy().hasHeightForWidth())
        self.settings_conformation_buttons.setSizePolicy(sizePolicy)
        self.settings_conformation_buttons.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.settings_conformation_buttons.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.settings_conformation_buttons.setOrientation(QtCore.Qt.Horizontal)
        self.settings_conformation_buttons.setStandardButtons(QtWidgets.QDialogButtonBox.Apply|QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.settings_conformation_buttons.setCenterButtons(False)
        self.settings_conformation_buttons.setObjectName("settings_conformation_buttons")
        self.gridLayout.addWidget(self.settings_conformation_buttons, 2, 0, 1, 1)

        self.retranslateUi(SettingsDialog)
        self.settings_tab_widget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(SettingsDialog)

    def retranslateUi(self, SettingsDialog):
        _translate = QtCore.QCoreApplication.translate
        SettingsDialog.setWindowTitle(_translate("SettingsDialog", "Dialog"))
        self.choose_descriptors_label.setText(_translate("SettingsDialog", "Choose method for calculating descriptors"))
        self.settings_tab_widget.setTabText(self.settings_tab_widget.indexOf(self.descriptor_settings_tab), _translate("SettingsDialog", "Descriptors"))
        self.similar_images_count_text_label.setText(_translate("SettingsDialog", "How many similar images to display"))
        self.similar_images_columns_selection_text_label.setText(_translate("SettingsDialog", "How many columns should similar images take"))
        self.similar_images_count_label.setText(_translate("SettingsDialog", "0"))
        self.similar_images_columns_count_text_label.setText(_translate("SettingsDialog", "1"))
        self.settings_tab_widget.setTabText(self.settings_tab_widget.indexOf(self.similar_images_settings_tab), _translate("SettingsDialog", "Similar images"))
        self.choose_similarities_label_2.setText(_translate("SettingsDialog", "Choose similarities"))
        self.settings_tab_widget.setTabText(self.settings_tab_widget.indexOf(self.similarities_settings), _translate("SettingsDialog", "Similarities"))

