from slide_analysis.descriptors.constants import COLOR_RANGE
from slide_analysis.descriptors.histogram_descriptor_class import HistogramDescriptor
from slide_analysis.descriptors.test_descriptor_class import TestDescriptor

all_descriptors = [TestDescriptor, HistogramDescriptor]
